#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

apk add --no-cache --no-progress git make musl-dev go

# Configure Go
export GOROOT="/usr/lib/go"
export GOPATH="/go"
export PATH="/go/bin:$PATH"

PROJECT_ROOT="$(dirname $0)/.."
cd ${PROJECT_ROOT}

# build the component-cli
make cross-build EFFECTIVE_VERSION="$(cat VERSION)"

COMPONENT_CLI="${PROJECT_ROOT}/dist/componentcli-linux-amd64"

# overwrite included component-cli to also test it
cp ${COMPONENT_CLI} /bin/component-cli

# copy base component descriptor to temporary directory
COMPONENT_ARCHIVE_PATH="/tmp/ca"
COMPONENT_DESCRIPTOR_FILE_PATH="$COMPONENT_ARCHIVE_PATH/component-descriptor.yaml"
mkdir -p "$COMPONENT_ARCHIVE_PATH"
cp "$BASE_DEFINITION_PATH" "$COMPONENT_DESCRIPTOR_FILE_PATH"

printf "> Add Linux Binary\n"
ARTIFACT_PATH="$(pwd)/dist/componentcli-linux-amd64"
cat <<EOF | $COMPONENT_CLI ca resources add "$COMPONENT_ARCHIVE_PATH" -
name: cli-binary-linux
type: executable
extraIdentity:
  os: linux
  arch: amd64
relation: local
input:
  type: file
  path: ${ARTIFACT_PATH}
EOF

printf "> Add Darwin Binary\n"
ARTIFACT_PATH="$(pwd)/dist/componentcli-darwin-amd64"
cat <<EOF | $COMPONENT_CLI ca resources add "$COMPONENT_ARCHIVE_PATH" -
name: cli-binary-darwin
type: executable
extraIdentity:
  os: darwin
  arch: amd64
relation: local
input:
  type: file
  path: ${ARTIFACT_PATH}
EOF


# add component references
image_vector_component_name="github.com/gardener/image-vector"
image_vector_component_version="v0.0.0"
if go list -m -mod=mod all | grep "$image_vector_component_name"; then
  image_vector_component_version=$(go list -m -mod=mod all | grep "$image_vector_component_name" | awk '{ print $2 }')
fi

cat <<EOF | $COMPONENT_CLI ca component-references add "$COMPONENT_ARCHIVE_PATH" -
name: image-vector
componentName: ${image_vector_component_name}
version: ${image_vector_component_version}
EOF

printf "> Modified Component Descriptor\n"
cat "$COMPONENT_DESCRIPTOR_FILE_PATH"

printf "> add ca to ctf\n"
$COMPONENT_CLI ctf add "$CTF_PATH" -f "$COMPONENT_ARCHIVE_PATH"
