#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

apk add --no-cache --no-progress git make musl-dev go

# Configure Go
export GOROOT="/usr/lib/go"
export GOPATH="/go"
export PATH="/go/bin:$PATH"

cd "$(dirname $0)/.."

# install the component-cli
make install

# copy base component descriptor to temporary directory
COMPONENT_ARCHIVE_PATH="/tmp/ca"
COMPONENT_DESCRIPTOR_FILE_PATH="$COMPONENT_ARCHIVE_PATH/component-descriptor.yaml"
mkdir -p "$COMPONENT_ARCHIVE_PATH"
cp "$BASE_DEFINITION_PATH" "$COMPONENT_DESCRIPTOR_FILE_PATH"

#component-cli gardener-ci init
ARTIFACT_PATH="$(which "component-cli")"
cat <<EOF | component-cli ca resources add --archive="$COMPONENT_ARCHIVE_PATH"
name: cli-binary-linux
extraIdentity:
  os: "linux"
  arch: "amd64"
relation: local
input:
  type: "file"
  path: "$ARTIFACT_PATH"
EOF

# copy modified component-descriptor to
cp "$COMPONENT_DESCRIPTOR_FILE_PATH" "$COMPONENT_DESCRIPTOR_PATH"